---

- name: create settings directory
  sudo_user: "{{project.user}}"
  file: >
    state=directory
    path={{project.root}}/code/config

- name: create settings file
  sudo_user: "{{project.user}}"
  file: >
    state=link
    path={{project.root}}/code/config/lilliput_settings.py
    src={{project.root}}/code/lilliput/settings.py

