---

- name: install pip requirements
  sudo: true
  sudo_user: "{{project.user}}"
  pip: >
    requirements={{project.root}}/code/requirements.txt
    virtualenv={{project.virtualenv}}
    virtualenv_site_packages=yes
  notify:
    - restart uwsgi

- name: create settings directory
  sudo_user: "{{project.user}}"
  file: >
    state=directory
    path={{project.root}}/code/config

- name: create settings file
  sudo_user: "{{project.user}}"
  file: >
    state=link
    path={{project.root}}/code/config/lilliput_settings.py
    src={{project.root}}/code/lilliput/settings.py

